name: Python

on:
  push:
    branches:
      - main
      - dev*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake python3.8-dev gdb

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: CMake configure
        run: |
          source .venv/bin/activate
          mkdir build
          mkdir install
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install \
            -DPY_INSTALL_PATH=${{github.workspace}}/.venv/lib/python3.8/site-packages \
            -DLIB_TESTS=OFF \
            -DBUILD_LIB_ACS_INT=ON \
            ../cpp
      
      - name: Build lib
        run: |
          cmake --build ${{github.workspace}}/build -j $(nproc)
          cmake --build ${{github.workspace}}/build --target install
      
      - name: Execute tests
        run: |
          source .venv/bin/activate
          gdb --batch --ex="run" --ex="bt" --ex="quit" --args python3 -m unittest discover -s int-bindings/test -p '*_test.py'
